version: '3.8'

services:
  samwaf:
    image: samwaf:cus-1.4-beta2
    container_name: samwaf
    privileged: true
    ports:
      - "26666:26666"
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/app/conf
      - ./data:/app/data
      - ./logs:/app/logs
      - ./ssl:/app/ssl

    restart: always